/* Generated By:JavaCC: Do not edit this line. simplejavaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface simplejavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLELINECOMMENT = 9;
  /** RegularExpression Id. */
  int FOR = 10;
  /** RegularExpression Id. */
  int UNDERLINE = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int DO = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int CLASS = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int NEW = 20;
  /** RegularExpression Id. */
  int READ = 21;
  /** RegularExpression Id. */
  int PRINT = 22;
  /** RegularExpression Id. */
  int PRINTLN = 23;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 24;
  /** RegularExpression Id. */
  int IDENTIFIER = 25;
  /** RegularExpression Id. */
  int PLUS = 26;
  /** RegularExpression Id. */
  int SEMICOLON = 27;
  /** RegularExpression Id. */
  int MINUS = 28;
  /** RegularExpression Id. */
  int MULTIPLY = 29;
  /** RegularExpression Id. */
  int DIVIDE = 30;
  /** RegularExpression Id. */
  int LPAREN = 31;
  /** RegularExpression Id. */
  int RPAREN = 32;
  /** RegularExpression Id. */
  int LBRACE = 33;
  /** RegularExpression Id. */
  int RBRACE = 34;
  /** RegularExpression Id. */
  int LBRACKET = 35;
  /** RegularExpression Id. */
  int RBRACKET = 36;
  /** RegularExpression Id. */
  int PERIOD = 37;
  /** RegularExpression Id. */
  int COMMA = 38;
  /** RegularExpression Id. */
  int EQUALEQUAL = 39;
  /** RegularExpression Id. */
  int GETS = 40;
  /** RegularExpression Id. */
  int NOTEQUALTO = 41;
  /** RegularExpression Id. */
  int NOT = 42;
  /** RegularExpression Id. */
  int LESSTHAN = 43;
  /** RegularExpression Id. */
  int LESSTHANOREQUALTO = 44;
  /** RegularExpression Id. */
  int GREATERTHAN = 45;
  /** RegularExpression Id. */
  int GREATERTHANOREQUALTO = 46;
  /** RegularExpression Id. */
  int AND = 47;
  /** RegularExpression Id. */
  int OR = 48;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 3>",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "\"\\f\"",
    "\"\\r\"",
    "<SINGLELINECOMMENT>",
    "\"for\"",
    "\"_\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"else\"",
    "\"class\"",
    "\"true\"",
    "\"false\"",
    "\"return\"",
    "\"new\"",
    "\"read\"",
    "\"print\"",
    "\"println\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "\"+\"",
    "\";\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "\"==\"",
    "\"=\"",
    "\"!=\"",
    "\"!\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
  };

}
